---
# tasks file for nginx

## enable epel

# - name: setup epel
#  yum:
#    name: "{{ item }}"
#    state: installed
#  with_items:
#    - epel-release

- name: enable ipv4 non local bind
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes

- name: install nginx and rngd
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - nginx
    - rng-tools
  notify:
    - enable nginx
    - restart nginx
    - enable rngd

- name: check if nginx is compiled with dynamic or static stream module
  shell: /sbin/nginx -V 2>&1 | grep -q ' --with-stream '
  register: static_stream
  changed_when: false
  failed_when: false
  check_mode: no

- name: install mod-stream
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - nginx-mod-stream
  when:
    - static_stream.rc != 0

- name: create default nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx

- name: Create systemd service override directory
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory

- name: Copy systemd overrides
  template:
    src: systemd_override.conf.j2
    dest: /etc/systemd/system/nginx.service.d/override.conf
  notify:
    - reload systemd

# avoid overriding of default.conf by package updates
- name: create empty dummy default.conf
  copy:
    content: '# do not remove this file'
    dest: /etc/nginx/conf.d/default.conf
    owner: nginx
    group: nginx
    mode: 0644
  notify:
    - reload nginx

- meta: flush_handlers
