---
dependency:
  name: gilt
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ../.yamllint
platforms:
  - name: instance
    # systemd needs a privileged container atm.
    privileged: true
    image: centos:7
    command: /sbin/init
    env:
      container: docker
    security_opts:
      - apparmor=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
      - SYSLOG
provisioner:
  name: ansible
  config_options:
    defaults:
      jinja2_extensions: jinja2.ext.do
  options:
    vault-id: ~/.ssh/vault_pass.txt
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      config: ../.flake8
