---
- name: Prepare
  hosts: generic_loadbalancer
  gather_facts: False
  tasks:
    - name: install dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - iproute
        - sysvinit-tools
        - epel-release

    - name: create facts dir
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: set fact
      copy:
        content: |
          [run]
          true = 1
        dest: /etc/ansible/facts.d/molecule.fact
